hyprland_packages:
  - hyprland
  - hyprland-preview-share-picker
  - hyprlock
  - hyprpicker
  - hypridle
  - waybar
  - rofi-wayland
  - xdg-desktop-portal
  - xdg-desktop-portal-gtk
  - xdg-desktop-portal-hyprland
  - qt5-wayland
  - qt6-wayland
  - pipewire
  - pipewire-alsa
  - pipewire-pulse
  - pipewire-jack
  - pipewire-audio
  - wireplumber
  - polkit
  - polkit-gnome
  - wl-clipboard
  - dunst
  - lxappearance
  - alacritty
  - ttf-meslo-nerd
  - ttf-jetbrains-mono
  - ttf-cascadia-mono-nerd
  - arandr
  - nautilus
  - bluez
  - bluez-libs
  - bluetui
  - swaybg
  - swayosd
  - dbus

desktop_config_files:
  - src: "{{dotfiles_path}}/hypr/"
    dest: /home/{{dev_username}}/.config/hypr/
    owner: myute
    group: myute
    mode: "0775"
  - src: "{{dotfiles_path}}/waybar/"
    dest: /home/{{dev_username}}/.config/waybar/
    owner: myute
    group: myute
    mode: "0775"
  - src: "{{dotfiles_path}}/rofi/"
    dest: /home/{{dev_username}}/.config/rofi/
    owner: myute
    group: myute
    mode: "0775"
  - src: "{{dotfiles_path}}/dunst/"
    dest: /home/{{dev_username}}/.config/dunst/
    owner: myute
    group: myute
    mode: "0775"
  - src: "{{dotfiles_path}}/alacritty.toml"
    dest: /home/{{dev_username}}/.config/alacritty/alacritty.toml
    owner: myute
    group: myute
    mode: "0775"
