---
- name: install rust
  tags: rust
  ansible.builtin.shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

- name: install alacritty
  tags: rust
  ansible.builtin.shell: ~/.cargo/bin/cargo install alacritty

- name: install eza
  tags: rust
  ansible.builtin.shell: ~/.cargo/bin/cargo install eza

- name: install fish
  tags: fish
  become: true
  community.general.pacman:
    name: starship,fish
    state: latest

- name: set shell
  tags: fish
  become: true
  user:
    name: "{{ user.name }}"
    shell: /usr/bin/fish

- name: check if fzf is installed
  tags : fzf
  stat:
    path: ~/.fzf
  register: fzf

- name: install fzf
  tags: fzf
  ansible.builtin.shell:  git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf && ~/.fzf/install --all
  when: not fzf.stat.exists
