---
arch_hostname: default
arch_username: myute
kde_enabled: true
docker_enabled: true
gaming_amd_enabled: true
citrix_enabled: false
logind_lid_ignore: false

monitors:
  - name: DP-2
    resolution: 3440x1440@165
    position: auto
    scale: 1
