---
- name: install all tools
  hosts: all
  become: true
  remote_user: myu
  tasks:
    - name: update server
      apt:
        upgrade: yes
        update_cache: yes

    - name: install tools
      apt:
        name: git,nodejs,neovim,ripgrep,wget,gcc,tmux
        state: absent

