---
- name: Copy config files
  tags: copy, i3
  copy: 
    src: "{{ playbook_dir }}/../../dotfiles/i3"
    dest: ~/.config/

- name: Copy fish config files
  tags: copy, fish
  copy: 
    src: "{{ playbook_dir }}/../../dotfiles/fish"
    dest: ~/.config/

- name: copy nvim config
  tags: nvim,copy
  copy:
    src: "{{ playbook_dir }}/../../dotfiles/nvim"
    dest: ~/.config/
    force: true

- name: Copy tmux config files
  tags: copy, tmux
  copy: 
    src: "{{ playbook_dir }}/../../dotfiles/.tmux.conf"
    dest: ~/

- name: Copy alacritty config files
  tags: copy, alacritty
  copy: 
    src: "{{ playbook_dir }}/../../dotfiles/alacritty.toml"
    dest: ~/.config/alacritty/
