---
- name: Install packages
  community.general.pacman:
    name:
      - pacman-contrib
      - xdg-user-dirs
      - xdg-desktop-portal
    state: present
  become: true

- name: Start systemd service - xdg-user-dirs-update.service
  ansible.builtin.systemd:
    name: xdg-user-dirs-update.service
    state: started
    enabled: yes
    scope: user

- name: Start systemd service - paccache.timer
  ansible.builtin.systemd:
    name: paccache.timer
    state: started
    enabled: yes
  become: true

- name: Detect GPU
  # ansible.builtin.shell: set -o pipefail && lspci -v | grep -A1 -e VGA -e 3D  # noqa command-instead-of-shell
  ansible.builtin.shell: set -o pipefail && lspci | grep -i 'VGA\|3D\|display'  # noqa command-instead-of-shell
  register: gpu_result
  changed_when: no

- name: Install GPU drivers (AMD)
  community.general.pacman:
    name:
      - mesa
      - mesa-utils
      # https://wiki.archlinux.org/title/Xorg
      - xf86-video-amdgpu
      # https://wiki.archlinux.org/title/Hardware_video_acceleration
      - mesa-vdpau
      - libva-mesa-driver
      # https://wiki.archlinux.org/title/Vulkan
      - vulkan-radeon
    state: present
  become: true
  when: ("'radeon' in gpu_result.stdout.lower()") or ("'amd/ati' in gpu_result.stdout.lower()")

- name: Install GPU drivers (Intel)
  community.general.pacman:
    name:
      - mesa
      - mesa-utils
      # https://wiki.archlinux.org/title/Xorg
      - xf86-video-intel
      # https://wiki.archlinux.org/title/Hardware_video_acceleration
      - intel-media-driver
      - libva-intel-driver
      # https://wiki.archlinux.org/title/Vulkan
      - vulkan-intel
    state: present
  become: true
  when: "'intel' in gpu_result.stdout.lower()"

- name: Install GPU drivers (Nvidia)
  community.general.pacman:
    name:
      - mesa
      - mesa-utils
      # https://wiki.archlinux.org/title/Xorg
      - nvidia
      # https://wiki.archlinux.org/title/Hardware_video_acceleration
      - nvidia-utils
    state: present
  become: true
  when: "'nvidia' in gpu_result.stdout.lower()"

- name: Upgrade system
  community.general.pacman:
    update_cache: yes
    upgrade: yes
  become: true

